//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FindPrime", ReplyAction="http://tempuri.org/IService1/FindPrimeResponse")]
        string FindPrime(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FindPrime", ReplyAction="http://tempuri.org/IService1/FindPrimeResponse")]
        System.Threading.Tasks.Task<string> FindPrimeAsync(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SumDigits", ReplyAction="http://tempuri.org/IService1/SumDigitsResponse")]
        string SumDigits(string num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SumDigits", ReplyAction="http://tempuri.org/IService1/SumDigitsResponse")]
        System.Threading.Tasks.Task<string> SumDigitsAsync(string num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReverseString", ReplyAction="http://tempuri.org/IService1/ReverseStringResponse")]
        string ReverseString(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReverseString", ReplyAction="http://tempuri.org/IService1/ReverseStringResponse")]
        System.Threading.Tasks.Task<string> ReverseStringAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrintHTMLTAG", ReplyAction="http://tempuri.org/IService1/PrintHTMLTAGResponse")]
        string PrintHTMLTAG(string tag, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrintHTMLTAG", ReplyAction="http://tempuri.org/IService1/PrintHTMLTAGResponse")]
        System.Threading.Tasks.Task<string> PrintHTMLTAGAsync(string tag, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SortNumbers", ReplyAction="http://tempuri.org/IService1/SortNumbersResponse")]
        string SortNumbers(string sortType, string fiveNumbers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SortNumbers", ReplyAction="http://tempuri.org/IService1/SortNumbersResponse")]
        System.Threading.Tasks.Task<string> SortNumbersAsync(string sortType, string fiveNumbers);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ConsoleApp1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ConsoleApp1.ServiceReference1.IService1>, ConsoleApp1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string FindPrime(int num) {
            return base.Channel.FindPrime(num);
        }
        
        public System.Threading.Tasks.Task<string> FindPrimeAsync(int num) {
            return base.Channel.FindPrimeAsync(num);
        }
        
        public string SumDigits(string num) {
            return base.Channel.SumDigits(num);
        }
        
        public System.Threading.Tasks.Task<string> SumDigitsAsync(string num) {
            return base.Channel.SumDigitsAsync(num);
        }
        
        public string ReverseString(string str) {
            return base.Channel.ReverseString(str);
        }
        
        public System.Threading.Tasks.Task<string> ReverseStringAsync(string str) {
            return base.Channel.ReverseStringAsync(str);
        }
        
        public string PrintHTMLTAG(string tag, string data) {
            return base.Channel.PrintHTMLTAG(tag, data);
        }
        
        public System.Threading.Tasks.Task<string> PrintHTMLTAGAsync(string tag, string data) {
            return base.Channel.PrintHTMLTAGAsync(tag, data);
        }
        
        public string SortNumbers(string sortType, string fiveNumbers) {
            return base.Channel.SortNumbers(sortType, fiveNumbers);
        }
        
        public System.Threading.Tasks.Task<string> SortNumbersAsync(string sortType, string fiveNumbers) {
            return base.Channel.SortNumbersAsync(sortType, fiveNumbers);
        }
    }
}
